"""Core types, constants, GPU resolution, OOM wrapping, and small primitives."""

from orka._impl import (
    BackgroundWriter,
    CappedOutOfMemoryError,
    CUBLAS_WORKSPACE_SLOP_BYTES,
    ORKA_VERSION,
    PayloadEstimate,
    estimate_payload,
    _apply_gpu_memory_cap,
    _BG_WRITER,
    _cuda_sm_major,
    _derive_seed,
    _dir_size,
    _human_bytes,
    _is_cuda_oom,
    _is_numpy_array,
    _is_torch_tensor,
    _maybe_fallback_cuda_to_cpu,
    _parse_params,
    _product,
    _report_progress,
    _require_non_empty,
    _resolve_torch_device,
    _safe_exp,
    _safe_tensor_name,
    _source_signature,
    _supports_numpy_backend,
    _torch_f32,
    _wrap_capped_oom,
)
