"""Pre-VQ pipeline: normalization (row-l2/col-l2/block-max/awq/awq-block-max/slrq-block),
rotation (orthogonal/hadamard), and outlier extraction with on-disk sidecars."""

from orka._impl import (
    _FP16_MAX,
    _apply_block_max_scales,
    _apply_block_max_scales_numpy,
    _apply_col_l2_scales,
    _apply_col_l2_scales_numpy,
    _apply_normalization,
    _apply_row_l2_scales,
    _apply_row_l2_scales_numpy,
    _extract_outliers,
    _fwht_numpy,
    _fwht_torch,
    _generate_orthogonal_numpy,
    _generate_orthogonal_torch,
    _normalize_tensor_awq_block_max_torch,
    _normalize_tensor_awq_numpy,
    _normalize_tensor_awq_torch,
    _normalize_tensor_block_max_numpy,
    _normalize_tensor_block_max_torch,
    _normalize_tensor_col_l2_numpy,
    _normalize_tensor_col_l2_torch,
    _normalize_tensor_row_l2_numpy,
    _normalize_tensor_row_l2_torch,
    _normalize_tensor_slrq_block_numpy,
    _normalize_tensor_slrq_block_torch,
    _read_outliers,
    _rotate_tensor_to_2d,
    _tensor_rotation_seed,
    _unrotate_flat,
    _write_outliers,
)
